name = "blitz"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[build]
command = "vite build"

[[rules]]
type = "Data"
globs = ["**/*.json"]
fallthrough = true
